services:
  app:
    container_name: katask-app
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./backend/:/var/www/html
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    container_name: katask-web
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./backend/:/var/www/html

  node:
    container_name: katask-node
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/usr/src/app
    environment:
      - WATCHPACK_POLLING=true
    tty: true

  db:
    container_name: katask-db
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/msql/conf.d
    environment:
      MYSQL_DATABASE: katask
      MYSQL_USER: katask
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
